title: Louisa Swintosky
logo: Headshot.jpeg
description: |
  <div style="text-align:center;">
    <img src="Headshot.jpeg" alt="Louisa Swintosky Headshot" style="max-width: 200px;">
    <p>M.S. Candidate in Analytics at the Institute for Advanced Analytics, NC State University</p>
    <p>
      <a href="https://github.com/louisaswin">View My GitHub Profile</a> | 
      <a href="https://www.linkedin.com/in/louisa-swintosky">LinkedIn</a> | 
      <a href="/Swintosky_Louisa.pdf">Resume</a>
    </p>
  </div>
show_downloads: no
theme: jekyll-theme-cayman
